### ISSUE TITLE
[discussion] question about speed : C instead of C++ ?

### ISSUE THREAD

**Issue by vtorri** [Samsung/rlottie#163]
hello

currently, the code is written in C++. Do you think that C could improve the speed of the rendering ?

**Comment by hermet** [comment]
@vtorri we are providing C wrapper additionally as the interface but internal implementation are totally based on C++, we have no plan to support c version and i don't think C is better than C++ in performance wise in this design since most bottle neck would be in rasterization and this implementation is out of language scope.

**Comment by vtorri** [comment]
thanks for the explanation
