### ISSUE TITLE
A way to clear cache?

### ISSUE THREAD

**Issue by msva** [Samsung/rlottie#222]
Is it any way to somehow wipe current cache in rlottie's public API?
It can be useful in the case of preventing memory leakage in long-running apps, or, say, in the case of a need to forcefully reload cached animation with new data.

**Comment by smohantty** [comment]
@msva ,
Could you bit elaborate on your use case ?
for ex:
1. I don't want to use the cache at all.
2. I want to selectively use cache for some resource.
3. I want to use cache all the time but need a way to flush the cache when ever i want.
4. I want to use cache all the time but for some resource force a reload (Don't use the data from the cache if exists).

**Comment by msva** [comment]
Well, that was a theoretic question (I just planning to use it in future, but 
have no active project with it ATM), so, I'm interested about all the cases 
you defined.


But we can take Telegram Desktop client as real-life example: it's author 
bundles rlottie and builds it with disabled cache because, let me quote him,

> Building rlottie with cache enabled will cause real problems with animated 
stickers, because rlottie cache is a static storage that is never cleared 
while the app is running, so while you will view more stickers it will just 
become a growing memory leak. So the correct way, unfortunately, is to build 
it with caching disabled.

So, I guess, in that exactly case he need a way to at least drop some "out of 
date" items from cache. Or, maybe, limit cache storage capacity by the number 
of items.

// or we can cast him here: @john-preston





> @msva ,
> Could you bit elaborate on your use case ?
> for ex:
> 1. I don't want to use the cache at all.
> 2. I want to selectively use cache for some resource.
> 3. I want to use cache all the time but need a way to flush the cache when
> ever i want. 4. I want to use cache all the time but for some resource
> force a reload (Don't use the data from the cache if exists).

**Comment by smohantty** [comment]
@msva , 
I totally agree with your point. 
I added cache keeping the Ui element in mind (like button background  , radio button or check box) which will have multiple instance of the same resource so it make sense to cache the model data after parsing lottie file.
Because of all the above use case am struggling to come with some  Api that is simple yet give control to  user what and how they manage the cache Data.

Maybe We can add some kind of cache policy to rlottie::loadFromFile() api 
lets say 

Enum CachePolicy
{ 
    Never, // do't cache
    Strong , // cache always
    Weak    // cache always but has lower priority during cache eviction.
}
loadFromFile(const std::string &path, CachePolicy cahe= CachePolicy::Never );

and for customizing maximum number of items in the cache ,
i can give a build configuration like CACHE_SIZE.

and once the cache is full , it will start evicting the items with cache policy starting from Weak and then Strong

Then Only Use Case left is how to handle the theme change?
maybe a new rlottie::cache_fluch() api which will clear the cache // personally i don't like this api :)

So we have 2 choice 
Choice 1:
 upadated api  loadFromFile(const std::string &path, CachePolicy cahe= CachePolicy::Never );
  Build Configuration: CACHE_SIZE
  new api   : rlottie::cache_flush()

Choic 2:
      
       upadated api  loadFromFile(const std::string &path, const std::string &key={}, CachePolicy cahe= 
                                                                                                                                CachePolicy::Never );
      Build Configuration: CACHE_SIZE

      Note: In choice 2 , user gives the cache_key, so if theme change he has to generate a new cache key with file stamp or any other means .


Or if you guys have any more suggestion then we can discuss and come up with a set of Apis that will
take care of most of the cases when cache is enabled.
