### ISSUE TITLE
[rlottie] create a web interface to test and showcase rlottie library

### ISSUE THREAD

**Issue by smohantty** [Samsung/rlottie#25]
Would like to have similar web interface like in skia lottie.
https://skottie.skia.org

1. Figure out how to host the page
      - convert the library into web assembly and send it to the client. or 
      - run the application in the server and send the render image back to client.

**Comment by hermet** [comment]
One idea by me.
We could add a lottie glue layer, which calls our native binary functions, for script (i.e js5)  and the script calls lottie.js functions to draw generate images.
This approach seems a little awkward in performance wise, but in reality, that may work for rlottie. a single visited webpage install rlottie library automatically, then make it use it.
https://medium.com/@tarkus/how-to-call-c-c-code-from-node-js-86a773033892

**Comment by akanad** [comment]
I can say without doubt that we have to convert the library into wasm to provide a way to test the library through web. but the only problem is that we don't have a person who has skills for it. 

(roughly) we need to make 

1. web-front 
   user will access to our static-server. 
2.  wrapper or binding for native library 
   and user's client(web browser) will execute those js files that served from our static-server
3. library that is pre-built as wasm(web-assembly) with webgl backend
   client run this wasm and render through webgl onto canvas on web-browser.

and if we complete to make those things. we can provide a way to test the library through static web-server.


as @smohantty said, we can render as gif or something in server then serve it to client. but it will take a lot of resources. and i don't think that it's totally pointless to do that  so that it can't be an option. 


and lastly, node is not about client side something. node is about server side programming that uses javascript. which means that this is about a way to make a self-hosted node-based web application. so that this can't be an option neither.

**Comment by smohantty** [comment]
@akanad ,
  we can split the task into steps .
 1. create the front end for loading json file (maybe drag and drop in to browser) and the UI (play , pause and slider)
2. find a way to create memory in JS and pass to a simple emscripten function.
3. build rlottie as wasm and expose required api to JS (for passing json file , passing buffer to render into)

**Comment by smohantty** [comment]
first version of this can be found in https://smohantty.github.io/

**Comment by smohantty** [comment]
Moved the rlottie viewer to http://www.rlottie.com/
