### ISSUE TITLE
change lottie speed

### ISSUE THREAD

**Issue by Aghajari** [Samsung/rlottie#261]
hello again.
is there anyway to change lottie animation speed?

**Comment by hermet** [comment]
hi, Aghajari.

rlottie doesn't handle the animation loop itself, because the loop must be belonged to its own applications or  platform core system that runs the application process.

That means rlottie just provide some apis to check frame count and animation duration time by users.

Obviously, the applications just need to indicate the frame number (or normalized progress value) working on their main(animation) loop. If you wanna increase/decrease lottie animation speed, then you can control setting current frame number or progress value by increasing or decreasing them.

Please check it APIs(functionalities) out of which ui system your application working on. There must be a convenient animation controllers with custom interpolator to customize animation speed.
