### ISSUE TITLE
Accelerate rlottie using OpenVG

### ISSUE THREAD

**Issue by alinpopescu** [Samsung/rlottie#268]
Hi,

I'm new to lottie and I would like to know how feasible is it to accelerate lottie using HW implemented OpenVG? At the moment I'm using standard lottie implementation using Pixman and it takes a lot of CPU time on a mobile device.

Thanks,
Alin

**Comment by hermet** [comment]
Hi, @alinpopescu 

We've also looked forward to accelerate rasterizer with HW. Still it's a just one pending task because it must be a very huge task. We hope but yet we have no exact plan for it. If we do, there are 3 points to be figured out before we start this task.

1. Is it really better to use gl acceleration for rasterzier? Then how we could achieve this to get the improvement in performance/memory usage wise.

2. As one separate rendering library, How we design this to integrate with main graphics stack with the least performance loss? Most platforms have its own gl drawing context, The best performance would be to draw directly on the main gl context so that we can skip using fbo as possible. The safer and standard method is to draw onto the shared buffer with the dynamic texture egl surface. But still we have to consider the gl context switch if there a lot of lottie animation instances on the screen.

3. Which vector acceleration project is feasible and the best for our rlottie project? OpenVG or some other else such as fastuidraw.

**Comment by hermet** [comment]
@alinpopescu + just wondering, which project or product would you do like to use this for? Can you share us?

**Comment by vtorri** [comment]
https://github.com/memononen/nanovg ?
