### ISSUE TITLE
Allow Vector's freetype and stb to use operating system libraries.

### ISSUE THREAD

**Issue by fire** [Samsung/rlottie#420]
What is the difference between standard freetype and vector's copy? Can I remove vector's freetype?

Note: The same reasoning goes for stb to be using standard versions.

Most Linux distributions require that embedded libraries be using the operating system one.

**Comment by smohantty** [comment]
@fire ,
rlottie dosen't keep a copy of the freetype , it only has the sandalone greyraster and stroker code . which compiles down to 20-30KB code against 1MB of freetype library. other reason is rlottie uses multi threaded renderer so we did some change to make it work for that. so it won't be straight forward do directly use the freetype and the library size reduction will not be that much.

Regarding STB, its a header only library so there is no separate stb library . and as its part of rlottie namespace only disadvantage is the library size .(another 15-20K). but if you building rlottie as part of an application and you already has some kind of image loading support . then you can modify the rlottie image loader to use that instead of using STB library.

Hope this helps.
