### ISSUE TITLE
missing layers

### ISSUE THREAD

**Issue by mythodeia** [Samsung/rlottie#448]
Hello,
we are having a problem rendering the json file attached in demoTest.json.zip.
[demoTest.json.zip](https://github.com/Samsung/rlottie/files/5473647/demoTest.json.zip)

the correct should be:
<img width="743" alt="correct" src="https://user-images.githubusercontent.com/1748458/97846601-e8e84200-1cf6-11eb-9541-ecb30cde36d5.png">

however its showing as:
![wrong](https://user-images.githubusercontent.com/1748458/97846619-ee458c80-1cf6-11eb-8d62-2a50737c136e.png)

we are using the latest version of the library.

**Comment by rlottie** [comment]
@mythodeia ,
hi checked the resource . the missing layer has a rectangle shape with height 0. that's why we drop generating the path information for the empty rectangle. Maybe can be changed to generate a line when the rectangle have 0 width or 0 height. will put a patch fro the same.

Thanks for the reporting.

**Comment by smohantty** [comment]
fixed pushed for the above issue #449

**Comment by mythodeia** [comment]
@smohantty i will reply as soon as this is tested. Thanks for the support 👍

**Comment by mythodeia** [comment]
@smohantty the issue is now resolved. Thanks 👍
